plot.retention <- function(
  x,                # <retention> object. Could be generated by e.g. mixpanelGetRetention.
  y,                # Unused.
  percentages=TRUE, # Output as counts or percentages? Default TRUE.
  omitLast=TRUE,    # Omit last value per series? Useful for Mixpanel data, because last
                    # value is usually based on partial data!
  colors,           # Colors. Optional.
  ...               # Unused.
) {
  ## Get data.
  d = if(percentages) x$retainPerc else x$retainCount
  nCohorts = nrow(d)
  nPeriods = ncol(d) - ifelse(omitLast, 1, 0)
  
  if(missing(colors))
    colors = 1:nPeriods
  
  ## Case 1: one retention line per cohort; x axis shows Calendar Date.
  plot(c(1, nPeriods), range(d, na.rm=T), type="n", xlab="", ylab="", axes=F)
  axis(1, 1:nPeriods, x$dates[1:nPeriods]); axis(2); axis(4)
  for (i in 1:nCohorts) {
    len = nPeriods - (i - 1)
    lines(i:nPeriods, d[i, 1:len], col=colors[i])
  }
  
  ## Case 2: one retention line per cohort; x axis synchronizes cohort start dates.
  plot(c(1, nPeriods), range(d, na.rm=T), type="n", xlab="", ylab="", axes=F)
  axis(1, 1:nPeriods, 1:nPeriods); axis(2); axis(4)
  for (i in 1:nCohorts) {
    len = nPeriods - (i - 1)
    lines(1:len, d[i, 1:len], col=colors[i])
  }
}


